### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by johan-westin-private** [jasonrbriggs/stomp.py#378]
Hi,

Thank you for a fine and very usefull Python package!!

Today I got the below fatal error, using stomp.py==8.0.0 (which depends on pyOpenSSL==20.0.1):

Traceback (most recent call last):
  File "/projects/my_receiver/default/bin/my_receiver-request-receiver", line 5, in <module>
    from my_receiver.main.request_receiver import main
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/my_receiver/__init__.py", line 3, in <module>
    from .exception import (
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/my_receiver/exception.py", line 14, in <module>
    from my_commons import MyException
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/my_commons/__init__.py", line 293, in <module>
    from .config.setting import settings  # do not move this
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/my_commons/config/__init__.py", line 75, in <module>
    from .ioc_configurator import configure, set_root_dir_path
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/my_commons/config/ioc_configurator.py", line 13, in <module>
    from my_commons.common.simple_workflow_context import SimpleWorkflowContext
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/my_commons/common/__init__.py", line 37, in <module>
    from .stomp_connect import stomp_connect
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/my_commons/common/stomp_connect.py", line 9, in <module>
    import stomp
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/stomp/__init__.py", line 13, in <module>
    import stomp.connect as connect
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/stomp/connect.py", line 9, in <module>
    from stomp.transport import *
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/stomp/transport.py", line 38, in <module>
    import OpenSSL
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "/projects/my_receiver/1.0.0+/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

When install pyOpenSSL==22.0.0 with

	python -m pip install --upgrade pip setuptools wheel pyOpenSSL==22.0.0

Installing collected packages: pyOpenSSL
  Attempting uninstall: pyOpenSSL
    Found existing installation: pyOpenSSL 20.0.1
    Uninstalling pyOpenSSL-20.0.1:
      Successfully uninstalled pyOpenSSL-20.0.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
stomp-py 8.0.0 requires PyOpenSSL<21.0.0,>=20.0.1, but you have pyopenssl 22.0.0 which is incompatible.

and ignoring the ERROR it works fine.

Which action do you propose?

Best regards,
Johan Westin

**Comment by johan-westin-private** [comment]
OS: CentOS    Linux release 7.9.2009
Linux kernel:   3.10.0-1160.24.1.el7.x86_64
OpenSSL:       1.1
Python:           3.7.2 (build with GCC 8.2.0)

**Comment by jertel** [comment]
On Feb 16, an issue was created, requesting to upgrade to PyOpenSSL 22.0: https://github.com/jasonrbriggs/stomp.py/issues/371

Later that day this commit was pushed, effectively upgrading PyOpenSSL to 22.0: https://github.com/jasonrbriggs/stomp.py/commit/000de5e2032323bfc928e90f6047b03ef2438de5

Based on that it appears the code base is ready to go, and now we're waiting for a new pip package release.

However, it might be better to remove the dependency on PyOpenSSL altogether, and switch stomp/transport.py:56 to use the cryptography package directly to [load the certificate](https://cryptography.io/en/latest/x509/reference/). PyOpenSSL is [not recommended](https://github.com/pyca/pyopenssl) for use at this point.

**Comment by johan-westin-private** [comment]
My workaround is to pin cryptography==36.0.2

**Comment by eisraeli** [comment]
I've encountered the same issue... Following...

**../../../.local/share/virtualenvs/p/lib/python3.9/site-packages/stomp/__init__.py:13: in <module>
    import stomp.connect as connect
../../../.local/share/virtualenvs/p/lib/python3.9/site-packages/stomp/connect.py:9: in <module>
    from stomp.transport import *
../../../.local/share/virtualenvs/p/lib/python3.9/site-packages/stomp/transport.py:38: in <module>
    import OpenSSL
../../../.local/share/virtualenvs/p/lib/python3.9/site-packages/OpenSSL/__init__.py:8: in <module>
    from OpenSSL import crypto, SSL
../../../.local/share/virtualenvs/p/lib/python3.9/site-packages/OpenSSL/crypto.py:1556: in <module>
    class X509StoreFlags(object):
../../../.local/share/virtualenvs/p/lib/python3.9/site-packages/OpenSSL/crypto.py:1577: in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
E   AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'**

**Comment by jertel** [comment]
Some good news.. The pyca team released cryptography 37.0.1 which restored the symbol that this older PyOpenSSL package uses. They will be removing it again soon, so they still advise projects to upgrade to the latest PyOpenSSL lib. But for now we can continue using the Stomp 8.0.0 package.

**Comment by jasonrbriggs** [comment]
I've changed the code to use x509 from the cryptography module itself, and removed the dependency on PyOpenSSL.  Added bonus... code is ever-so-slightly clean as well.

Version 8.0.1: https://pypi.org/project/stomp.py/8.0.1/

**Comment by johan-westin-private** [comment]
Great news, thank you very much!
